# -*- coding: utf-8 -*-
"""app_Fraud Transaction

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t6ODl3DEygpnje27ts6qQE5UHmRO_4IW
"""

import streamlit as st
import joblib
import numpy as np

# Default model path
MODEL_PATH = "FailedTxn_DT.pkl"

# Load the model safely
model = joblib.load(MODEL_PATH)

# App title
st.title("FraudTransaction Prediction Model")

# Input fields
failed_txn = st.number_input("No. of Failed Transactions", min_value=0, step=1)
is_weekend = st.selectbox("Is it on Weekend?", ["No", "Yes"])
device_type = st.selectbox("Device Type", ["Mobile", "Desktop", "Tablet", "Other"])
txn_amount = st.number_input("Transaction Amount", min_value=0.0, format="%.2f")

# Convert categorical inputs
is_weekend_num = 1 if is_weekend == "Yes" else 0
device_map = {"Mobile": 0, "Desktop": 1, "Tablet": 2, "Other": 3}
device_num = device_map[device_type]

# Prediction button
if st.button("Predict Fraud Transaction"):
    input_data = np.array([[failed_txn, is_weekend_num, device_num, txn_amount]])
    prediction = model.predict(input_data)[0]

    if prediction == 1:
        st.write("### 🚨 This transaction is likely FRAUDULENT.")
    else:
        st.write("### ✅ This transaction is NOT fraudulent.")